// Generated by tauri-specta. Do not edit: run `cargo test -p photovault export_bindings`.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getAppInfo: () => typedError<AppInfo, ApiError>(__TAURI_INVOKE("get_app_info")),
	getSettings: () => typedError<AppSettings, ApiError>(__TAURI_INVOKE("get_settings")),
	saveSettings: (settings: AppSettings) => typedError<AppSettings, ApiError>(__TAURI_INVOKE("save_settings", { settings })),
	/**  Volume containing `path` (free/total space for the sidebar footer). */
	getVolumeInfo: (path: string) => typedError<{
	/**  Human label: volume name on Windows, last mount-point component on Linux. */
	label: string,
	mountPoint: string,
	totalBytes: number,
	availableBytes: number,
	removable: boolean,
} | null, ApiError>(__TAURI_INVOKE("get_volume_info", { path })),
	/**  Native folder picker. `None` when the user cancels. */
	pickFolder: () => typedError<string | null, ApiError>(__TAURI_INVOKE("pick_folder")),
	openLogsDir: () => typedError<null, ApiError>(__TAURI_INVOKE("open_logs_dir")),
	listLibraries: () => typedError<Library[], ApiError>(__TAURI_INVOKE("list_libraries")),
	createLibrary: (name: string, rootPath: string) => typedError<Library, ApiError>(__TAURI_INVOKE("create_library", { name, rootPath })),
	renameLibrary: (libraryId: string, name: string) => typedError<Library, ApiError>(__TAURI_INVOKE("rename_library", { libraryId, name })),
	/**  Point a library at its folder's new location (drive letter / mount point changed). */
	relocateLibrary: (libraryId: string, rootPath: string) => typedError<Library, ApiError>(__TAURI_INVOKE("relocate_library", { libraryId, rootPath })),
	/**  Remove a library from the catalog (and its thumbnails). Photos on disk are untouched. */
	deleteLibrary: (libraryId: string) => typedError<null, ApiError>(__TAURI_INVOKE("delete_library", { libraryId })),
	getLibraryStats: (libraryId: string) => typedError<LibraryStats, ApiError>(__TAURI_INVOKE("get_library_stats", { libraryId })),
	/**
	 *  Start scanning a library in the background.
	 *  Progress: `scanProgressEvent`; end: `scanCompleteEvent` or `scanErrorEvent`.
	 */
	scanLibrary: (libraryId: string) => typedError<null, ApiError>(__TAURI_INVOKE("scan_library", { libraryId })),
	cancelScan: () => typedError<null, ApiError>(__TAURI_INVOKE("cancel_scan")),
	/**  Library being scanned right now, if any. */
	getScanningLibrary: () => typedError<string | null, ApiError>(__TAURI_INVOKE("get_scanning_library")),
	/**  A page of the gallery. Pass `nextCursor` from the previous page to continue. */
	listMedia: (libraryId: string, cursor: string | null, limit: number) => typedError<MediaPage, ApiError>(__TAURI_INVOKE("list_media", { libraryId, cursor, limit })),
	getMedia: (mediaId: string) => typedError<MediaItem, ApiError>(__TAURI_INVOKE("get_media", { mediaId })),
	getMediaNavigation: (mediaId: string) => typedError<MediaNavigation, ApiError>(__TAURI_INVOKE("get_media_navigation", { mediaId })),
};

/** Events */
export const events = {
	scanCompleteEvent: makeEvent<ScanCompleteEvent>("scan-complete-event"),
	scanErrorEvent: makeEvent<ScanErrorEvent>("scan-error-event"),
	scanProgressEvent: makeEvent<ScanProgressEvent>("scan-progress-event"),
};

/* Types */
/**  Error returned by every command: stable `code` + pt-BR `message`. */
export type ApiError = {
	code: string,
	message: string,
};

export type AppInfo = {
	version: string,
	dataMode: DataMode,
	baseDir: string,
	logsDir: string,
	/**  Path of the archived v0.x catalog, when it was archived on this start. */
	archivedLegacyCatalog: string | null,
};

export type AppSettings = {
	theme: Theme,
	/**  Library shown when the app opens. */
	activeLibraryId: string | null,
	/**  Parallel file reads during analysis (2 for USB HDDs, higher for SSDs). Used from phase 2. */
	ioConcurrency: number,
	/**  CPU workers for analysis; 0 = automatic (cores - 1). Used from phase 2. */
	cpuConcurrency: number,
};

/**  Where the runtime data lives. */
export type DataMode = 
/**  Next to the executable (or AppImage): `portable.flag` present, or a debug build. */
"portable" | 
/**  Forced by the `PHOTOVAULT_HOME` environment variable. */
"custom" | 
/**  OS data directory (no flag, or the app folder is read-only). */
"system";

export type Library = {
	id: string,
	uid: string,
	name: string,
	rootPath: string,
	createdAt: string,
	lastScanAt: string | null,
	/**  Whether `root_path` is reachable right now (e.g. external drive plugged in). */
	connected: boolean,
};

export type LibraryStats = {
	photos: number,
	videos: number,
	favorites: number,
	totalBytes: number,
};

/**  Media item as exposed to the frontend. */
export type MediaItem = {
	id: string,
	libraryId: string,
	relativePath: string,
	filename: string,
	extension: string,
	mediaType: MediaType,
	fileSize: number,
	width: number | null,
	height: number | null,
	durationMs: number | null,
	capturedAt: string | null,
	dateSource: string | null,
	cameraMake: string | null,
	cameraModel: string | null,
	isFavorite: boolean,
	indexedAt: string,
};

export type MediaNavigation = {
	/**  Previous item in gallery order (newer). */
	prevId: string | null,
	/**  Next item in gallery order (older). */
	nextId: string | null,
	/**  1-based position and total, for "12 / 426". */
	position: number,
	total: number,
};

/**  One page of the gallery. Pass `next_cursor` back to get the following page. */
export type MediaPage = {
	items: MediaItem[],
	nextCursor: string | null,
};

export type MediaType = "image" | "video";

export type ScanCompleteEvent = ScanSummary;

export type ScanErrorEvent = {
	libraryId: string,
	error: ApiError,
};

export type ScanPhase = "discovering" | "indexing";

export type ScanProgress = {
	libraryId: string,
	phase: ScanPhase,
	processed: number,
	/**  0 while discovering (total still unknown). */
	total: number,
	currentPath: string,
};

export type ScanProgressEvent = ScanProgress;

export type ScanSummary = {
	libraryId: string,
	total: number,
	processed: number,
	newFiles: number,
	modifiedFiles: number,
	errors: number,
	cancelled: boolean,
};

export type Theme = "light" | "dark" | "system";

export type VolumeInfo = {
	/**  Human label: volume name on Windows, last mount-point component on Linux. */
	label: string,
	mountPoint: string,
	totalBytes: number,
	availableBytes: number,
	removable: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

