// Generated by tauri-specta. Do not edit: run `cargo test -p photovault export_bindings`.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getAppInfo: () => typedError<AppInfo, ApiError>(__TAURI_INVOKE("get_app_info")),
	getSettings: () => typedError<AppSettings, ApiError>(__TAURI_INVOKE("get_settings")),
	saveSettings: (settings: AppSettings) => typedError<AppSettings, ApiError>(__TAURI_INVOKE("save_settings", { settings })),
	/**  Volume containing `path` (free/total space for the sidebar footer). */
	getVolumeInfo: (path: string) => typedError<{
	/**  Human label: volume name on Windows, last mount-point component on Linux. */
	label: string,
	mountPoint: string,
	totalBytes: number,
	availableBytes: number,
	removable: boolean,
} | null, ApiError>(__TAURI_INVOKE("get_volume_info", { path })),
	/**  Native folder picker. `None` when the user cancels. */
	pickFolder: () => typedError<string | null, ApiError>(__TAURI_INVOKE("pick_folder")),
	openLogsDir: () => typedError<null, ApiError>(__TAURI_INVOKE("open_logs_dir")),
	listLibraries: () => typedError<Library[], ApiError>(__TAURI_INVOKE("list_libraries")),
	createLibrary: (name: string, rootPath: string) => typedError<Library, ApiError>(__TAURI_INVOKE("create_library", { name, rootPath })),
	renameLibrary: (libraryId: string, name: string) => typedError<Library, ApiError>(__TAURI_INVOKE("rename_library", { libraryId, name })),
	/**  Point a library at its folder's new location (drive letter / mount point changed). */
	relocateLibrary: (libraryId: string, rootPath: string) => typedError<Library, ApiError>(__TAURI_INVOKE("relocate_library", { libraryId, rootPath })),
	/**  Remove a library from the catalog (and its thumbnails). Photos on disk are untouched. */
	deleteLibrary: (libraryId: string) => typedError<null, ApiError>(__TAURI_INVOKE("delete_library", { libraryId })),
	getLibraryStats: (libraryId: string) => typedError<LibraryStats, ApiError>(__TAURI_INVOKE("get_library_stats", { libraryId })),
	/**
	 *  Start scanning a library in the background.
	 *  Progress: `scanProgressEvent`; end: `scanCompleteEvent` or `scanErrorEvent`.
	 */
	scanLibrary: (libraryId: string) => typedError<null, ApiError>(__TAURI_INVOKE("scan_library", { libraryId })),
	cancelScan: () => typedError<null, ApiError>(__TAURI_INVOKE("cancel_scan")),
	/**  Library being scanned right now, if any. */
	getScanningLibrary: () => typedError<string | null, ApiError>(__TAURI_INVOKE("get_scanning_library")),
	/**
	 *  A page of the gallery. Pass `nextCursor` from the previous page to continue
	 *  (with the same query).
	 */
	listMedia: (libraryId: string, query: MediaQuery, cursor: string | null, limit: number) => typedError<MediaPage, ApiError>(__TAURI_INVOKE("list_media", { libraryId, query, cursor, limit })),
	countMedia: (libraryId: string, filter: MediaFilter) => typedError<MediaCount, ApiError>(__TAURI_INVOKE("count_media", { libraryId, filter })),
	getMedia: (mediaId: string) => typedError<MediaItem, ApiError>(__TAURI_INVOKE("get_media", { mediaId })),
	/**  Position, total and neighbours of an item inside a gallery context (viewer). */
	getMediaContext: (mediaId: string, query: MediaQuery, radius: number) => typedError<MediaContext, ApiError>(__TAURI_INVOKE("get_media_context", { mediaId, query, radius })),
	/**  Returns the updated items. */
	setFavorite: (mediaIds: string[], favorite: boolean) => typedError<MediaItem[], ApiError>(__TAURI_INVOKE("set_favorite", { mediaIds, favorite })),
	/**  Manual albums containing the item. */
	getMediaAlbums: (mediaId: string) => typedError<AlbumRef[], ApiError>(__TAURI_INVOKE("get_media_albums", { mediaId })),
	getOverview: (libraryId: string) => typedError<LibraryOverview, ApiError>(__TAURI_INVOKE("get_overview", { libraryId })),
	getTimeline: (libraryId: string, filter: MediaFilter) => typedError<TimelineBucket[], ApiError>(__TAURI_INVOKE("get_timeline", { libraryId, filter })),
	/**  Filter menu options. */
	listPlaces: (libraryId: string) => typedError<PlaceOption[], ApiError>(__TAURI_INVOKE("list_places", { libraryId })),
	listCameras: (libraryId: string) => typedError<CameraOption[], ApiError>(__TAURI_INVOKE("list_cameras", { libraryId })),
	listAlbums: (libraryId: string) => typedError<Album[], ApiError>(__TAURI_INVOKE("list_albums", { libraryId })),
	getAlbum: (albumId: string) => typedError<Album, ApiError>(__TAURI_INVOKE("get_album", { albumId })),
	/**  `rule` set = smart album (filled by the rule); otherwise a manual album. */
	createAlbum: (libraryId: string, name: string, rule: {
	mediaType?: MediaType | null,
	/**  `true` = only favorites. */
	favorite?: boolean | null,
	year?: number | null,
	/**  1–12. Without `year`, that month in any year. */
	month?: number | null,
	/**  1–31; needs `year` and `month`. */
	day?: number | null,
	/**  Inclusive range, "YYYY-MM-DD". */
	dateFrom?: string | null,
	dateTo?: string | null,
	placeId?: number | null,
	/**  Exact `camera_model`. */
	camera?: string | null,
	albumId?: string | null,
	/**
	 *  Free text (Ctrl+K): years and month names become date filters, the rest is
	 *  matched against file name, folder, place and album names.
	 */
	text?: string | null,
} | null) => typedError<Album, ApiError>(__TAURI_INVOKE("create_album", { libraryId, name, rule })),
	renameAlbum: (albumId: string, name: string) => typedError<Album, ApiError>(__TAURI_INVOKE("rename_album", { albumId, name })),
	updateAlbumRule: (albumId: string, rule: MediaFilter) => typedError<Album, ApiError>(__TAURI_INVOKE("update_album_rule", { albumId, rule })),
	/**  Removes the album only; photos stay in the library. */
	deleteAlbum: (albumId: string) => typedError<null, ApiError>(__TAURI_INVOKE("delete_album", { albumId })),
	/**  Returns how many items were added (already present ones are skipped). */
	addToAlbum: (albumId: string, mediaIds: string[]) => typedError<number, ApiError>(__TAURI_INVOKE("add_to_album", { albumId, mediaIds })),
	removeFromAlbum: (albumId: string, mediaIds: string[]) => typedError<number, ApiError>(__TAURI_INVOKE("remove_from_album", { albumId, mediaIds })),
	/**  `mediaId` null = automatic cover (newest photo). */
	setAlbumCover: (albumId: string, mediaId: string | null) => typedError<Album, ApiError>(__TAURI_INVOKE("set_album_cover", { albumId, mediaId })),
	/**  State of the background analysis queue. */
	getJobProgress: () => typedError<JobProgress, ApiError>(__TAURI_INVOKE("get_job_progress")),
	pauseJobs: () => typedError<JobProgress, ApiError>(__TAURI_INVOKE("pause_jobs")),
	resumeJobs: () => typedError<JobProgress, ApiError>(__TAURI_INVOKE("resume_jobs")),
	/**  Files the pipeline could not fully process (unsupported format, corrupt, unreadable). */
	listJobFailures: (limit: number) => typedError<JobFailure[], ApiError>(__TAURI_INVOKE("list_job_failures", { limit })),
	/**  Re-queue every failed item. Returns how many. */
	retryFailedJobs: () => typedError<number, ApiError>(__TAURI_INVOKE("retry_failed_jobs")),
};

/** Events */
export const events = {
	jobProgressEvent: makeEvent<JobProgressEvent>("job-progress-event"),
	mediaUpdatedEvent: makeEvent<MediaUpdatedEvent>("media-updated-event"),
	scanCompleteEvent: makeEvent<ScanCompleteEvent>("scan-complete-event"),
	scanErrorEvent: makeEvent<ScanErrorEvent>("scan-error-event"),
	scanProgressEvent: makeEvent<ScanProgressEvent>("scan-progress-event"),
};

/* Types */
export type Album = {
	id: string,
	libraryId: string,
	name: string,
	kind: AlbumKind,
	/**  Smart albums only. */
	rule: MediaFilter | null,
	mediaCount: number,
	/**  Chosen cover, or the newest item with a thumbnail. */
	cover: MediaItem | null,
	createdAt: string,
};

export type AlbumKind = "manual" | "smart";

export type AlbumRef = {
	id: string,
	name: string,
};

/**  Error returned by every command: stable `code` + pt-BR `message`. */
export type ApiError = {
	code: string,
	message: string,
};

export type AppInfo = {
	version: string,
	dataMode: DataMode,
	baseDir: string,
	logsDir: string,
	/**  Path of the archived v0.x catalog, when it was archived on this start. */
	archivedLegacyCatalog: string | null,
};

export type AppSettings = {
	theme: Theme,
	/**  Library shown when the app opens. */
	activeLibraryId: string | null,
	/**  Parallel file reads during analysis (2 for USB HDDs, higher for SSDs). Used from phase 2. */
	ioConcurrency: number,
	/**  CPU workers for analysis; 0 = automatic (cores - 1). Used from phase 2. */
	cpuConcurrency: number,
};

export type CameraOption = {
	make: string | null,
	model: string,
	count: number,
};

/**  Where the runtime data lives. */
export type DataMode = 
/**  Next to the executable (or AppImage): `portable.flag` present, or a debug build. */
"portable" | 
/**  Forced by the `PHOTOVAULT_HOME` environment variable. */
"custom" | 
/**  OS data directory (no flag, or the app folder is read-only). */
"system";

export type JobFailure = {
	mediaId: string,
	libraryName: string,
	relativePath: string,
	error: string,
	attempts: number,
	updatedAt: string,
};

export type JobProgress = {
	/**  Working right now (false when idle or paused). */
	active: boolean,
	paused: boolean,
	/**  Waiting to be processed (includes items of disconnected libraries). */
	queued: number,
	/**  Processed since the queue last became busy. */
	doneInSession: number,
	/**  Items with a problem (see diagnostics). */
	failed: number,
	perMinute: number,
	etaSeconds: number | null,
	currentPath: string | null,
};

export type JobProgressEvent = JobProgress;

export type Library = {
	id: string,
	uid: string,
	name: string,
	rootPath: string,
	createdAt: string,
	lastScanAt: string | null,
	/**  Whether `root_path` is reachable right now (e.g. external drive plugged in). */
	connected: boolean,
};

export type LibraryOverview = {
	photos: number,
	videos: number,
	favorites: number,
	albums: number,
	/**  Newest first. */
	years: YearSummary[],
	/**  Hero image: a landscape favorite if there is one, else any landscape photo. */
	highlight: MediaItem | null,
};

export type LibraryStats = {
	photos: number,
	videos: number,
	favorites: number,
	totalBytes: number,
};

/**  Where an item sits in a gallery context (filter + order), for the viewer. */
export type MediaContext = {
	/**  1-based position and total, for "12 / 426". */
	position: number,
	total: number,
	/**  Neighbours in order (thumbnail strip); `items[index]` is the item itself. */
	items: MediaItem[],
	index: number,
};

export type MediaCount = {
	total: number,
	photos: number,
	videos: number,
};

/**  Every field is optional; unset fields don't restrict. All set fields combine with AND. */
export type MediaFilter = {
	mediaType?: MediaType | null,
	/**  `true` = only favorites. */
	favorite?: boolean | null,
	year?: number | null,
	/**  1–12. Without `year`, that month in any year. */
	month?: number | null,
	/**  1–31; needs `year` and `month`. */
	day?: number | null,
	/**  Inclusive range, "YYYY-MM-DD". */
	dateFrom?: string | null,
	dateTo?: string | null,
	placeId?: number | null,
	/**  Exact `camera_model`. */
	camera?: string | null,
	albumId?: string | null,
	/**
	 *  Free text (Ctrl+K): years and month names become date filters, the rest is
	 *  matched against file name, folder, place and album names.
	 */
	text?: string | null,
};

/**  Media item as exposed to the frontend. */
export type MediaItem = {
	id: string,
	libraryId: string,
	relativePath: string,
	filename: string,
	extension: string,
	mediaType: MediaType,
	fileSize: number,
	width: number | null,
	height: number | null,
	durationMs: number | null,
	capturedAt: string | null,
	dateSource: string | null,
	cameraMake: string | null,
	cameraModel: string | null,
	lens: string | null,
	iso: number | null,
	aperture: number | null,
	/**  "1/1200", "2"… */
	shutter: string | null,
	focalLength: number | null,
	gpsLat: number | null,
	gpsLon: number | null,
	placeName: string | null,
	/**  State; Brazilian states as their code ("RS"). */
	placeAdmin1: string | null,
	/**  ISO 3166-1 alpha-2 ("BR"). */
	placeCountry: string | null,
	isFavorite: boolean,
	/**  0 = thumbnails not generated yet; bumps when they are rewritten. */
	thumbVersion: number,
	indexedAt: string,
};

/**  One page of the gallery. Pass `next_cursor` back to get the following page. */
export type MediaPage = {
	items: MediaItem[],
	nextCursor: string | null,
};

export type MediaQuery = {
	filter?: MediaFilter,
	sort?: MediaSort,
};

export type MediaSort = 
/**  Capture date, newest first; undated last. */
"newest" | 
/**  Capture date, oldest first; undated last. */
"oldest" | 
/**  File name A→Z. */
"name" | 
/**  Largest files first. */
"largest";

export type MediaType = "image" | "video";

/**
 *  Items whose metadata/thumbnails changed; `removedIds` were merged into another
 *  record (moved files).
 */
export type MediaUpdatedEvent = {
	items: MediaItem[],
	removedIds: string[],
};

export type PlaceOption = {
	id: number,
	name: string,
	admin1: string | null,
	countryCode: string,
	count: number,
};

export type ScanCompleteEvent = ScanSummary;

export type ScanErrorEvent = {
	libraryId: string,
	error: ApiError,
};

export type ScanPhase = "discovering" | "indexing";

export type ScanProgress = {
	libraryId: string,
	phase: ScanPhase,
	processed: number,
	/**  0 while discovering (total still unknown). */
	total: number,
	currentPath: string,
};

export type ScanProgressEvent = ScanProgress;

export type ScanSummary = {
	libraryId: string,
	total: number,
	processed: number,
	newFiles: number,
	modifiedFiles: number,
	/**  Catalogued files no longer found (kept as `missing`, never deleted). */
	missingFiles: number,
	/**  Previously missing files that are back. */
	restoredFiles: number,
	errors: number,
	cancelled: boolean,
};

export type Theme = "light" | "dark" | "system";

/**  Month bucket; `year` 0 = undated. */
export type TimelineBucket = {
	year: number,
	/**  1–12; 0 for undated. */
	month: number,
	count: number,
};

export type VolumeInfo = {
	/**  Human label: volume name on Windows, last mount-point component on Linux. */
	label: string,
	mountPoint: string,
	totalBytes: number,
	availableBytes: number,
	removable: boolean,
};

export type YearSummary = {
	year: number,
	count: number,
	cover: MediaItem | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

