// Generated by tauri-specta. Do not edit: run `cargo test -p photovault export_bindings`.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getAppInfo: () => typedError<AppInfo, ApiError>(__TAURI_INVOKE("get_app_info")),
	getSettings: () => typedError<AppSettings, ApiError>(__TAURI_INVOKE("get_settings")),
	saveSettings: (settings: AppSettings) => typedError<AppSettings, ApiError>(__TAURI_INVOKE("save_settings", { settings })),
	/**  Volume containing `path` (free/total space for the sidebar footer). */
	getVolumeInfo: (path: string) => typedError<{
	/**  Human label: volume name on Windows, last mount-point component on Linux. */
	label: string,
	mountPoint: string,
	totalBytes: number,
	availableBytes: number,
	removable: boolean,
} | null, ApiError>(__TAURI_INVOKE("get_volume_info", { path })),
	/**  Native folder picker. `None` when the user cancels. */
	pickFolder: () => typedError<string | null, ApiError>(__TAURI_INVOKE("pick_folder")),
	openLogsDir: () => typedError<null, ApiError>(__TAURI_INVOKE("open_logs_dir")),
	listLibraries: () => typedError<Library[], ApiError>(__TAURI_INVOKE("list_libraries")),
	createLibrary: (name: string, rootPath: string) => typedError<Library, ApiError>(__TAURI_INVOKE("create_library", { name, rootPath })),
	renameLibrary: (libraryId: string, name: string) => typedError<Library, ApiError>(__TAURI_INVOKE("rename_library", { libraryId, name })),
	/**  Point a library at its folder's new location (drive letter / mount point changed). */
	relocateLibrary: (libraryId: string, rootPath: string) => typedError<Library, ApiError>(__TAURI_INVOKE("relocate_library", { libraryId, rootPath })),
	/**  Remove a library from the catalog (and its thumbnails). Photos on disk are untouched. */
	deleteLibrary: (libraryId: string) => typedError<null, ApiError>(__TAURI_INVOKE("delete_library", { libraryId })),
	getLibraryStats: (libraryId: string) => typedError<LibraryStats, ApiError>(__TAURI_INVOKE("get_library_stats", { libraryId })),
	/**
	 *  Start scanning a library in the background.
	 *  Progress: `scanProgressEvent`; end: `scanCompleteEvent` or `scanErrorEvent`.
	 */
	scanLibrary: (libraryId: string) => typedError<null, ApiError>(__TAURI_INVOKE("scan_library", { libraryId })),
	cancelScan: () => typedError<null, ApiError>(__TAURI_INVOKE("cancel_scan")),
	/**  Library being scanned right now, if any. */
	getScanningLibrary: () => typedError<string | null, ApiError>(__TAURI_INVOKE("get_scanning_library")),
	/**
	 *  A page of the gallery. Pass `nextCursor` from the previous page to continue
	 *  (with the same query).
	 */
	listMedia: (libraryId: string, query: MediaQuery, cursor: string | null, limit: number) => typedError<MediaPage, ApiError>(__TAURI_INVOKE("list_media", { libraryId, query, cursor, limit })),
	/**  Videos waiting for a thumbnail frame (captured by the WebView). */
	listPendingVideoFrames: (limit: number) => typedError<string[], ApiError>(__TAURI_INVOKE("list_pending_video_frames", { limit })),
	/**  A frame of the video (`data:image/jpeg;base64,…`) becomes its thumbnails. */
	saveVideoFrame: (mediaId: string, frame: string) => typedError<MediaItem, ApiError>(__TAURI_INVOKE("save_video_frame", { mediaId, frame })),
	/**  The WebView can't play this video: keep the icon. */
	failVideoFrame: (mediaId: string, reason: string) => typedError<null, ApiError>(__TAURI_INVOKE("fail_video_frame", { mediaId, reason })),
	countMedia: (libraryId: string, filter: MediaFilter) => typedError<MediaCount, ApiError>(__TAURI_INVOKE("count_media", { libraryId, filter })),
	getMedia: (mediaId: string) => typedError<MediaItem, ApiError>(__TAURI_INVOKE("get_media", { mediaId })),
	/**  Position, total and neighbours of an item inside a gallery context (viewer). */
	getMediaContext: (mediaId: string, query: MediaQuery, radius: number) => typedError<MediaContext, ApiError>(__TAURI_INVOKE("get_media_context", { mediaId, query, radius })),
	/**  Returns the updated items. */
	setFavorite: (mediaIds: string[], favorite: boolean) => typedError<MediaItem[], ApiError>(__TAURI_INVOKE("set_favorite", { mediaIds, favorite })),
	/**  Manual albums containing the item. */
	getMediaAlbums: (mediaId: string) => typedError<AlbumRef[], ApiError>(__TAURI_INVOKE("get_media_albums", { mediaId })),
	getOverview: (libraryId: string) => typedError<LibraryOverview, ApiError>(__TAURI_INVOKE("get_overview", { libraryId })),
	getTimeline: (libraryId: string, filter: MediaFilter) => typedError<TimelineBucket[], ApiError>(__TAURI_INVOKE("get_timeline", { libraryId, filter })),
	/**  Filter menu options. */
	listPlaces: (libraryId: string) => typedError<PlaceOption[], ApiError>(__TAURI_INVOKE("list_places", { libraryId })),
	listCameras: (libraryId: string) => typedError<CameraOption[], ApiError>(__TAURI_INVOKE("list_cameras", { libraryId })),
	listAlbums: (libraryId: string) => typedError<Album[], ApiError>(__TAURI_INVOKE("list_albums", { libraryId })),
	/**  Smart albums worth creating (trips, favorites/best per year, screenshots…). */
	listAlbumSuggestions: (libraryId: string) => typedError<AlbumSuggestion[], ApiError>(__TAURI_INVOKE("list_album_suggestions", { libraryId })),
	getAlbum: (albumId: string) => typedError<Album, ApiError>(__TAURI_INVOKE("get_album", { albumId })),
	/**  `rule` set = smart album (filled by the rule); otherwise a manual album. */
	createAlbum: (libraryId: string, name: string, rule: {
	mediaType?: MediaType | null,
	/**  `true` = only favorites. */
	favorite?: boolean | null,
	year?: number | null,
	/**  1–12. Without `year`, that month in any year. */
	month?: number | null,
	/**  1–31; needs `year` and `month`. */
	day?: number | null,
	/**  Inclusive range, "YYYY-MM-DD". */
	dateFrom?: string | null,
	dateTo?: string | null,
	placeId?: number | null,
	/**  Exact `camera_model`. */
	camera?: string | null,
	albumId?: string | null,
	/**
	 *  Free text (Ctrl+K): years and month names become date filters, the rest is
	 *  matched against file name, folder, place and album names.
	 */
	text?: string | null,
	/**  Technical quality level (phase 4). */
	quality?: QualityLevel | null,
	qualityFlag?: QualityFlag | null,
	/**  `true` = screenshots only (score above the configured threshold). */
	screenshot?: boolean | null,
	momentary?: MomentaryFilter | null,
	/**  Manual tag. */
	tag?: string | null,
	/**  Members of a duplicate/similar group or of a burst (viewer navigation). */
	groupId?: string | null,
	sequenceId?: string | null,
	/**  `true` = photos with pending review suggestions (phase 5). */
	review?: boolean | null,
	/**  Pending suggestions for this reason. */
	reviewReason?: ReviewReason | null,
	/**  `true` = the trash instead of the active photos. */
	trashed?: boolean | null,
	/**  Photos of a trip/event (phase 6). */
	eventId?: string | null,
	/**  Photos where this person appears (phase 7b). */
	personId?: string | null,
} | null) => typedError<Album, ApiError>(__TAURI_INVOKE("create_album", { libraryId, name, rule })),
	renameAlbum: (albumId: string, name: string) => typedError<Album, ApiError>(__TAURI_INVOKE("rename_album", { albumId, name })),
	updateAlbumRule: (albumId: string, rule: MediaFilter) => typedError<Album, ApiError>(__TAURI_INVOKE("update_album_rule", { albumId, rule })),
	/**  Removes the album only; photos stay in the library. */
	deleteAlbum: (albumId: string) => typedError<null, ApiError>(__TAURI_INVOKE("delete_album", { albumId })),
	/**  Returns how many items were added (already present ones are skipped). */
	addToAlbum: (albumId: string, mediaIds: string[]) => typedError<number, ApiError>(__TAURI_INVOKE("add_to_album", { albumId, mediaIds })),
	removeFromAlbum: (albumId: string, mediaIds: string[]) => typedError<number, ApiError>(__TAURI_INVOKE("remove_from_album", { albumId, mediaIds })),
	/**  `mediaId` null = automatic cover (newest photo). */
	setAlbumCover: (albumId: string, mediaId: string | null) => typedError<Album, ApiError>(__TAURI_INVOKE("set_album_cover", { albumId, mediaId })),
	/**  Counters of the "Organizar" menu. */
	getOrganizeCounts: (libraryId: string) => typedError<OrganizeCounts, ApiError>(__TAURI_INVOKE("get_organize_counts", { libraryId })),
	/**  Duplicate/similar groups or bursts, best candidate first in each. */
	listGroups: (libraryId: string, kind: GroupKind, offset: number, limit: number) => typedError<GroupPage, ApiError>(__TAURI_INVOKE("list_groups", { libraryId, kind, offset, limit })),
	/**  Quality, labels and groups of one item (info panel / viewer). */
	getMediaAnalysis: (mediaId: string) => typedError<MediaAnalysis, ApiError>(__TAURI_INVOKE("get_media_analysis", { mediaId })),
	/**  Returns the normalized tag. */
	addTag: (mediaIds: string[], tag: string) => typedError<string, ApiError>(__TAURI_INVOKE("add_tag", { mediaIds, tag })),
	removeTag: (mediaIds: string[], tag: string) => typedError<null, ApiError>(__TAURI_INVOKE("remove_tag", { mediaIds, tag })),
	listTags: (libraryId: string) => typedError<TagCount[], ApiError>(__TAURI_INVOKE("list_tags", { libraryId })),
	/**  Trips and events of a library, newest first (`ignored = true`: only the ignored ones). */
	listEvents: (libraryId: string, ignored: boolean) => typedError<EventSummary[], ApiError>(__TAURI_INVOKE("list_events", { libraryId, ignored })),
	getEvent: (eventId: string) => typedError<EventSummary, ApiError>(__TAURI_INVOKE("get_event", { eventId })),
	/**  One card per day of the event. */
	getEventDays: (eventId: string) => typedError<EventDay[], ApiError>(__TAURI_INVOKE("get_event_days", { eventId })),
	/**  Best photos of the event (highlight carousel). */
	getEventHighlights: (eventId: string, limit: number) => typedError<MediaItem[], ApiError>(__TAURI_INVOKE("get_event_highlights", { eventId, limit })),
	acceptEvent: (eventId: string) => typedError<EventSummary, ApiError>(__TAURI_INVOKE("accept_event", { eventId })),
	/**  Hide a suggestion; it is not suggested again. */
	ignoreEvent: (eventId: string) => typedError<EventSummary, ApiError>(__TAURI_INVOKE("ignore_event", { eventId })),
	restoreEvent: (eventId: string) => typedError<EventSummary, ApiError>(__TAURI_INVOKE("restore_event", { eventId })),
	/**  Title and/or dates; the event becomes "edited" (not changed by the app anymore). */
	updateEvent: (eventId: string, change: EventUpdate) => typedError<EventSummary, ApiError>(__TAURI_INVOKE("update_event", { eventId, change })),
	removeFromEvent: (eventId: string, mediaIds: string[]) => typedError<EventSummary, ApiError>(__TAURI_INVOKE("remove_from_event", { eventId, mediaIds })),
	/**  Several events become one (a trip without GPS split into days). */
	mergeEvents: (merge: EventMerge) => typedError<EventSummary, ApiError>(__TAURI_INVOKE("merge_events", { merge })),
	/**  Settings → IA local. */
	getAiStatus: () => typedError<AiStatus, ApiError>(__TAURI_INVOKE("get_ai_status")),
	/**
	 *  The user agreed: download the models (the app's only network access), then load them
	 *  and start the analysis.
	 */
	downloadAiModels: (models: AiPackage) => typedError<null, ApiError>(__TAURI_INVOKE("download_ai_models", { models })),
	cancelAiDownload: () => typedError<null, ApiError>(__TAURI_INVOKE("cancel_ai_download")),
	/**  Delete the models and what they produced; the app goes back to working without them. */
	removeAiModels: (models: AiPackage) => typedError<null, ApiError>(__TAURI_INVOKE("remove_ai_models", { models })),
	/**  Pessoas: named people, then suggestions (hidden ones only when asked). */
	listPeople: (libraryId: string, includeHidden: boolean) => typedError<PersonSummary[], ApiError>(__TAURI_INVOKE("list_people", { libraryId, includeHidden })),
	getPerson: (libraryId: string, personId: string) => typedError<PersonSummary, ApiError>(__TAURI_INVOKE("get_person", { libraryId, personId })),
	/**  Faces in a photo (info panel, viewer). */
	getMediaFaces: (mediaId: string) => typedError<FaceInfo[], ApiError>(__TAURI_INVOKE("get_media_faces", { mediaId })),
	/**  Faces of a person, to review ("not this person"). */
	getPersonFaces: (libraryId: string, personId: string, limit: number) => typedError<FaceInfo[], ApiError>(__TAURI_INVOKE("get_person_faces", { libraryId, personId, limit })),
	/**  Named people, for suggesting while typing a name. */
	listPersonNames: () => typedError<PersonName[], ApiError>(__TAURI_INVOKE("list_person_names")),
	/**  Returns the id that remains (another person with that name absorbs this one). */
	renamePerson: (personId: string, name: string) => typedError<string, ApiError>(__TAURI_INVOKE("rename_person", { personId, name })),
	mergePeople: (targetId: string, sourceIds: string[]) => typedError<null, ApiError>(__TAURI_INVOKE("merge_people", { targetId, sourceIds })),
	setPersonHidden: (personId: string, hidden: boolean) => typedError<null, ApiError>(__TAURI_INVOKE("set_person_hidden", { personId, hidden })),
	setPersonCover: (personId: string, faceId: string) => typedError<null, ApiError>(__TAURI_INVOKE("set_person_cover", { personId, faceId })),
	/**  "Not this person". */
	removePersonFaces: (faceIds: string[]) => typedError<null, ApiError>(__TAURI_INVOKE("remove_person_faces", { faceIds })),
	/**  "This is Ana": returns the person's id. */
	nameFace: (faceId: string, name: string) => typedError<string, ApiError>(__TAURI_INVOKE("name_face", { faceId, name })),
	/**  Detect trips and events again in every library, now, with the current settings. */
	reclassifyEvents: (options: ReclassifyOptions) => typedError<EventCounts, ApiError>(__TAURI_INVOKE("reclassify_events", { options })),
	/**  Homes the photos point to, one per library (Settings: "Sua casa parece ser…"). */
	getDetectedHomes: () => typedError<Home[], ApiError>(__TAURI_INVOKE("get_detected_homes")),
	/**  Cities of the embedded GeoNames table, for choosing a home. */
	searchHomePlaces: (query: string) => typedError<Home[], ApiError>(__TAURI_INVOKE("search_home_places", { query })),
	/**  Counters of the Review screen (pending photos, per reason). */
	getReviewSummary: (libraryId: string) => typedError<ReviewSummary, ApiError>(__TAURI_INVOKE("get_review_summary", { libraryId })),
	/**  Every suggestion of one photo, decided or not (info panel). */
	getMediaReview: (mediaId: string) => typedError<ReviewEntry[], ApiError>(__TAURI_INVOKE("get_media_review", { mediaId })),
	/**  Pending reasons of the photos on screen (chips on the Review tiles). */
	getPendingReasons: (mediaIds: string[]) => typedError<MediaReasons[], ApiError>(__TAURI_INVOKE("get_pending_reasons", { mediaIds })),
	/**
	 *  Keep / ignore (or reopen) the suggestions of some photos, for every reason or one.
	 *  Returns the updated items (their review priority changed).
	 */
	decideReview: (mediaIds: string[], decision: Decision, reason: "EXACT_DUPLICATE" | "VISUAL_DUPLICATE" | "SIMILAR_SEQUENCE" | "BLURRY" | "DARK" | "OVEREXPOSED" | "LOW_RESOLUTION" | "SCREENSHOT" | "MOMENTARY" | "ACCIDENTAL" | "LOW_INFORMATION" | "EXAMPLE" | null) => typedError<MediaItem[], ApiError>(__TAURI_INVOKE("decide_review", { mediaIds, decision, reason })),
	listReviewHistory: (libraryId: string, cursor: string | null, limit: number) => typedError<HistoryPage, ApiError>(__TAURI_INVOKE("list_review_history", { libraryId, cursor, limit })),
	listExamples: () => typedError<ReviewExample[], ApiError>(__TAURI_INVOKE("list_examples")),
	/**  Photos of the catalog as examples. Returns how many were added. */
	addExamples: (mediaIds: string[], intent: ExampleIntent) => typedError<number, ApiError>(__TAURI_INVOKE("add_examples", { mediaIds, intent })),
	/**  Pick an image anywhere on disk as an example. `None` when the user cancels. */
	addExampleFromFile: (intent: ExampleIntent) => typedError<{
	id: string,
	intent: ExampleIntent,
	name: string,
	/**  `data:image/webp;base64,…` */
	thumbnail: string,
	/**  Photo of the catalog it came from (absent for files picked from disk). */
	mediaId: string | null,
	createdAt: string,
	/**  Photos currently suggested because of it. */
	matches: number,
} | null, ApiError>(__TAURI_INVOKE("add_example_from_file", { intent })),
	setExampleIntent: (exampleId: string, intent: ExampleIntent) => typedError<null, ApiError>(__TAURI_INVOKE("set_example_intent", { exampleId, intent })),
	removeExample: (exampleId: string) => typedError<null, ApiError>(__TAURI_INVOKE("remove_example", { exampleId })),
	/**  Send photos to the trash (library trash, or the system's if configured). */
	trashMedia: (mediaIds: string[]) => typedError<TrashResult, ApiError>(__TAURI_INVOKE("trash_media", { mediaIds })),
	restoreMedia: (mediaIds: string[], onConflict: OnConflict) => typedError<RestoreResult, ApiError>(__TAURI_INVOKE("restore_media", { mediaIds, onConflict })),
	/**  Delete trashed photos for good (the UI confirms twice). */
	purgeMedia: (mediaIds: string[]) => typedError<TrashResult, ApiError>(__TAURI_INVOKE("purge_media", { mediaIds })),
	emptyTrash: (libraryId: string) => typedError<TrashResult, ApiError>(__TAURI_INVOKE("empty_trash", { libraryId })),
	getTrashSummary: (libraryId: string) => typedError<TrashSummary, ApiError>(__TAURI_INVOKE("get_trash_summary", { libraryId })),
	/**  Original place and date of a trashed photo. */
	getTrashEntry: (mediaId: string) => typedError<{
	originalPath: string,
	deletedAt: string,
} | null, ApiError>(__TAURI_INVOKE("get_trash_entry", { mediaId })),
	/**  State of the background analysis queue. */
	getJobProgress: () => typedError<JobProgress, ApiError>(__TAURI_INVOKE("get_job_progress")),
	pauseJobs: () => typedError<JobProgress, ApiError>(__TAURI_INVOKE("pause_jobs")),
	resumeJobs: () => typedError<JobProgress, ApiError>(__TAURI_INVOKE("resume_jobs")),
	/**  Files the pipeline could not fully process (unsupported format, corrupt, unreadable). */
	listJobFailures: (limit: number) => typedError<JobFailure[], ApiError>(__TAURI_INVOKE("list_job_failures", { limit })),
	/**  Re-queue every failed item. Returns how many. */
	retryFailedJobs: () => typedError<number, ApiError>(__TAURI_INVOKE("retry_failed_jobs")),
};

/** Events */
export const events = {
	analysisUpdatedEvent: makeEvent<AnalysisUpdatedEvent>("analysis-updated-event"),
	jobProgressEvent: makeEvent<JobProgressEvent>("job-progress-event"),
	mediaUpdatedEvent: makeEvent<MediaUpdatedEvent>("media-updated-event"),
	peopleUpdatedEvent: makeEvent<PeopleUpdatedEvent>("people-updated-event"),
	scanCompleteEvent: makeEvent<ScanCompleteEvent>("scan-complete-event"),
	scanErrorEvent: makeEvent<ScanErrorEvent>("scan-error-event"),
	scanProgressEvent: makeEvent<ScanProgressEvent>("scan-progress-event"),
};

/* Types */
/**  Which set of models: "content" (search and scenes) or "faces" (people). */
export type AiPackage = "content" | "faces";

/**  Local AI: only used when the models were downloaded. */
export type AiSettings = {
	/**  Off: the model is unloaded (no content analysis, search by name only). */
	enabled?: boolean,
};

export type AiStatus = {
	/**  Content search and scenes (CLIP): files downloaded. */
	installed: boolean,
	/**  Loaded and in use (installed + enabled + loaded fine). */
	ready: boolean,
	/**  Download size of the models. */
	sizeBytes: number,
	/**  Photos with a content analysis / still waiting (all libraries). */
	indexed: number,
	pending: number,
	/**  People (face models, phase 7b). */
	faces: FaceStatus,
	download: DownloadState,
	/**  Why a model couldn't be loaded. */
	error: string | null,
};

export type Album = {
	id: string,
	libraryId: string,
	name: string,
	kind: AlbumKind,
	/**  Smart albums only. */
	rule: MediaFilter | null,
	mediaCount: number,
	/**  Chosen cover, or the newest item with a thumbnail. */
	cover: MediaItem | null,
	createdAt: string,
};

export type AlbumKind = "manual" | "smart";

export type AlbumRef = {
	id: string,
	name: string,
};

/**  A smart album the app proposes (PRD §18 "sugeridos"); created only on request. */
export type AlbumSuggestion = {
	name: string,
	rule: MediaFilter,
	count: number,
	cover: MediaItem | null,
};

/**
 *  Applied when groups and flags are recomputed, so changing them never requires
 *  re-reading the photos (raw metrics are stored).
 */
export type AnalysisSettings = {
	/**  pHash Hamming distance for "same picture" (resize, recompression). PRD: ≤ 4. */
	visualDistance?: number,
	/**
	 *  Colour difference (`metrics::color_distance`) up to which two photos with close
	 *  pHashes are still the same picture.
	 */
	colorDistance?: number | null,
	/**  pHash distance for "same scene". PRD: ≤ 12. */
	similarDistance?: number,
	/**  Similar photos must be this close in time. */
	similarWindowMinutes?: number,
	/**  Max gap between consecutive shots of a burst. */
	sequenceGapSeconds?: number,
	sequenceMinSize?: number,
	/**  Local sharpness (see `ImageMetrics::sharpness`) below this = blurry. */
	blurThreshold?: number | null,
	/**  Mean luminance (0–255) below this = dark. */
	darkThreshold?: number | null,
	/**  Fraction of blown-out pixels above this = overexposed. */
	overexposedFraction?: number | null,
	minMegapixels?: number | null,
	/**  Scores (0–1) from which a photo counts as screenshot / momentary. */
	screenshotThreshold?: number | null,
	momentaryThreshold?: number | null,
};

/**  Groups, quality flags and labels of a library were recomputed ("Organizar"). */
export type AnalysisUpdatedEvent = {
	libraryId: string,
};

/**  Error returned by every command: stable `code` + pt-BR `message`. */
export type ApiError = {
	code: string,
	message: string,
};

export type AppInfo = {
	version: string,
	dataMode: DataMode,
	baseDir: string,
	logsDir: string,
	/**  Path of the archived v0.x catalog, when it was archived on this start. */
	archivedLegacyCatalog: string | null,
};

export type AppSettings = {
	theme: Theme,
	/**  Library shown when the app opens. */
	activeLibraryId: string | null,
	/**  Parallel file reads during analysis (2 for USB HDDs, higher for SSDs). Used from phase 2. */
	ioConcurrency: number,
	/**  CPU workers for analysis; 0 = automatic (cores - 1). Used from phase 2. */
	cpuConcurrency: number,
	/**  Thresholds of the analysis heuristics (PRD §11–14). Absent in older catalogs. */
	analysis?: AnalysisSettings,
	/**  Suggestions and trash (PRD §15–16). Absent before v1.0. */
	review?: ReviewSettings,
	/**  Trips and events (PRD §17). Absent before v1.1. */
	events?: EventSettings,
	/**  Local AI (PRD §21). Absent before v2.0. */
	ai?: AiSettings,
};

export type CameraOption = {
	make: string | null,
	model: string,
	count: number,
};

/**  Where the runtime data lives. */
export type DataMode = 
/**  Next to the executable (or AppImage): `portable.flag` present, or a debug build. */
"portable" | 
/**  Forced by the `PHOTOVAULT_HOME` environment variable. */
"custom" | 
/**  OS data directory (no flag, or the app folder is read-only). */
"system";

/**  What the user decided about the suggestions of some photos. */
export type Decision = 
/**  "Manter": the photo stays, don't suggest it again for these reasons. */
"keep" | 
/**  "Ignorar sugestão": same effect, recorded as a dismissed suggestion. */
"ignore" | 
/**  Undo a keep/ignore (history): the suggestion comes back if it still applies. */
"reopen";

export type DownloadState = {
	running: boolean,
	/**  Package being (or last) downloaded (`ai::Package::id`). */
	package: string | null,
	doneBytes: number,
	totalBytes: number,
	/**  Last failure (network, checksum), for the settings page. */
	error: string | null,
};

/**  After a reclassification, in the library (ignored events not counted). */
export type EventCounts = {
	trips: number,
	events: number,
	/**  Of those, waiting for a decision. */
	suggested: number,
};

export type EventDay = {
	/**  "2025-07-11" */
	date: string,
	count: number,
	/**  Most photographed place of the day. */
	place: string | null,
	cover: MediaItem | null,
};

export type EventKind = "trip" | "event";

/**
 *  "Juntar": several events become one (e.g. a trip without GPS, split into one event per
 *  day). Takes their photos and the free photos between them (not in another accepted or
 *  edited event); the result is "edited", and suggestions left inside it go away.
 */
export type EventMerge = {
	eventIds: string[],
	kind: EventKind,
	/**  Empty/absent: from the place, or from the places of the photos. */
	title?: string | null,
	/**  Where it was, when the photos don't say ("Salvador, BA"). */
	place?: string | null,
};

export type EventRef = {
	id: string,
	kind: EventKind,
	status: EventStatus,
	title: string,
};

/**  Thresholds of the trip/event detection (PRD §17). */
export type EventSettings = {
	/**  A gap longer than this between two photos starts a new event. */
	gapHours?: number,
	/**  Farther than this from home (the most photographed place) = away. */
	tripMinKm?: number,
	/**  Away stretches this close in time (nights) belong to the same trip. */
	tripJoinHours?: number,
	/**  Smallest event / trip worth suggesting. */
	minEventItems?: number,
	minTripItems?: number,
	/**  Where the user lives; empty = the place photographed on the most days. */
	homes?: Home[],
};

export type EventStatus = "suggested" | "accepted" | "edited" | "ignored";

export type EventSummary = {
	id: string,
	kind: EventKind,
	status: EventStatus,
	title: string,
	/**  Local wall-clock times of the first and last photo. */
	startedAt: string,
	endedAt: string,
	/**  "Gramado, RS · Canela, RS" */
	placeSummary: string | null,
	photos: number,
	videos: number,
	/**  Distance from home (trips). */
	distanceKm: number | null,
	cover: MediaItem | null,
};

/**  What the user changes; unset fields stay. */
export type EventUpdate = {
	title?: string | null,
	/**  "YYYY-MM-DD" (inclusive): the photos of these days become the event's photos. */
	startDate?: string | null,
	endDate?: string | null,
	/**  The detection got it wrong: a trip that is an event, or the other way round. */
	kind?: EventKind | null,
};

export type ExampleIntent = 
/**  Suggest photos like this one for removal. */
"remove" | 
/**  Never suggest photos like this one (wins over "remove" when closer). */
"keep";

export type FaceInfo = {
	id: string,
	mediaId: string,
	/**  Box as fractions of the photo. */
	x: number | null,
	y: number | null,
	w: number | null,
	h: number | null,
	personId: string | null,
	personName: string | null,
	/**  The user put it in this person (or named it). */
	confirmed: boolean,
};

export type FaceStatus = {
	installed: boolean,
	ready: boolean,
	sizeBytes: number,
	/**  Photos already searched for faces / faces found / photos still waiting. */
	scanned: number,
	found: number,
	pending: number,
};

export type GroupKind = "exact_duplicate" | "visual_duplicate" | "similar" | "sequence";

export type GroupMember = {
	item: MediaItem,
	/**  pHash distance to the best candidate. */
	distance: number,
	quality: QualityLevel | null,
	sharpness: number | null,
};

export type GroupPage = {
	groups: MediaGroup[],
	total: number,
};

export type GroupRef = {
	id: string,
	kind: GroupKind,
	size: number,
	isBest: boolean,
};

export type HistoryEntry = {
	item: MediaItem,
	reason: ReviewReason,
	status: ReviewStatus,
	decidedAt: string,
};

export type HistoryPage = {
	entries: HistoryEntry[],
	nextCursor: string | null,
};

/**  A place the user calls home: trips are measured from the closest one. */
export type Home = {
	/**  "Porto Alegre, RS" */
	name: string,
	countryCode?: string | null,
	lat: number | null,
	lon: number | null,
};

export type JobFailure = {
	mediaId: string,
	libraryName: string,
	relativePath: string,
	error: string,
	attempts: number,
	updatedAt: string,
};

export type JobProgress = {
	/**  Working right now (false when idle or paused). */
	active: boolean,
	paused: boolean,
	/**  Waiting to be processed (includes items of disconnected libraries). */
	queued: number,
	/**  Processed since the queue last became busy. */
	doneInSession: number,
	/**  Items with a problem (see diagnostics). */
	failed: number,
	perMinute: number,
	etaSeconds: number | null,
	currentPath: string | null,
	/**  Recomputing duplicates, similar photos and bursts (after the queue drains). */
	grouping: boolean,
	/**  Photos waiting for the content analysis (local AI; 0 without the model). */
	contentPending: number,
	/**  Photos waiting to be searched for faces (0 without the face models). */
	facesPending: number,
};

export type JobProgressEvent = JobProgress;

export type LabelInfo = {
	/**  category | momentary | tag */
	dimension: string,
	value: string,
	score: number | null,
	manual: boolean,
};

export type Library = {
	id: string,
	uid: string,
	name: string,
	rootPath: string,
	createdAt: string,
	lastScanAt: string | null,
	/**  Whether `root_path` is reachable right now (e.g. external drive plugged in). */
	connected: boolean,
};

export type LibraryOverview = {
	photos: number,
	videos: number,
	favorites: number,
	albums: number,
	/**  Trips not ignored (suggested or accepted). */
	trips: number,
	/**  Newest first. */
	years: YearSummary[],
	/**  Hero image: a landscape favorite if there is one, else any landscape photo. */
	highlight: MediaItem | null,
};

export type LibraryStats = {
	photos: number,
	videos: number,
	favorites: number,
	totalBytes: number,
};

/**  Everything the info panel shows about an item's analysis. */
export type MediaAnalysis = {
	analyzed: boolean,
	quality: QualityLevel | null,
	flags: QualityFlag[],
	sharpness: number | null,
	brightness: number | null,
	/**  Active labels only (automatic above threshold, and manual tags). */
	labels: LabelInfo[],
	groups: GroupRef[],
	/**  Trips/events it belongs to (phase 6). */
	events: EventRef[],
	/**  What the photo shows (local AI, phase 7a); empty without the model. */
	scenes: SceneScore[],
};

/**  Where an item sits in a gallery context (filter + order), for the viewer. */
export type MediaContext = {
	/**  1-based position and total, for "12 / 426". */
	position: number,
	total: number,
	/**  Neighbours in order (thumbnail strip); `items[index]` is the item itself. */
	items: MediaItem[],
	index: number,
};

export type MediaCount = {
	total: number,
	photos: number,
	videos: number,
};

/**  Every field is optional; unset fields don't restrict. All set fields combine with AND. */
export type MediaFilter = {
	mediaType?: MediaType | null,
	/**  `true` = only favorites. */
	favorite?: boolean | null,
	year?: number | null,
	/**  1–12. Without `year`, that month in any year. */
	month?: number | null,
	/**  1–31; needs `year` and `month`. */
	day?: number | null,
	/**  Inclusive range, "YYYY-MM-DD". */
	dateFrom?: string | null,
	dateTo?: string | null,
	placeId?: number | null,
	/**  Exact `camera_model`. */
	camera?: string | null,
	albumId?: string | null,
	/**
	 *  Free text (Ctrl+K): years and month names become date filters, the rest is
	 *  matched against file name, folder, place and album names.
	 */
	text?: string | null,
	/**  Technical quality level (phase 4). */
	quality?: QualityLevel | null,
	qualityFlag?: QualityFlag | null,
	/**  `true` = screenshots only (score above the configured threshold). */
	screenshot?: boolean | null,
	momentary?: MomentaryFilter | null,
	/**  Manual tag. */
	tag?: string | null,
	/**  Members of a duplicate/similar group or of a burst (viewer navigation). */
	groupId?: string | null,
	sequenceId?: string | null,
	/**  `true` = photos with pending review suggestions (phase 5). */
	review?: boolean | null,
	/**  Pending suggestions for this reason. */
	reviewReason?: ReviewReason | null,
	/**  `true` = the trash instead of the active photos. */
	trashed?: boolean | null,
	/**  Photos of a trip/event (phase 6). */
	eventId?: string | null,
	/**  Photos where this person appears (phase 7b). */
	personId?: string | null,
};

export type MediaGroup = {
	id: string,
	kind: GroupKind,
	/**  Best candidate first (`members[0]`). */
	members: GroupMember[],
	/**  Bytes of the non-best members. */
	extraBytes: number,
};

/**  Media item as exposed to the frontend. */
export type MediaItem = {
	id: string,
	libraryId: string,
	relativePath: string,
	filename: string,
	extension: string,
	mediaType: MediaType,
	fileSize: number,
	width: number | null,
	height: number | null,
	durationMs: number | null,
	capturedAt: string | null,
	dateSource: string | null,
	cameraMake: string | null,
	cameraModel: string | null,
	lens: string | null,
	iso: number | null,
	aperture: number | null,
	/**  "1/1200", "2"… */
	shutter: string | null,
	focalLength: number | null,
	gpsLat: number | null,
	gpsLon: number | null,
	placeName: string | null,
	/**  State; Brazilian states as their code ("RS"). */
	placeAdmin1: string | null,
	/**  ISO 3166-1 alpha-2 ("BR"). */
	placeCountry: string | null,
	isFavorite: boolean,
	/**  0 = thumbnails not generated yet; bumps when they are rewritten. */
	thumbVersion: number,
	indexedAt: string,
	/**  In the trash (`relative_path` then points inside `.photovault-trash`). */
	inTrash: boolean,
	/**  Priority (1–1000) of its pending review suggestions; `None` = nothing to review. */
	reviewPriority: number | null,
};

/**  One page of the gallery. Pass `next_cursor` back to get the following page. */
export type MediaPage = {
	items: MediaItem[],
	nextCursor: string | null,
};

export type MediaQuery = {
	filter?: MediaFilter,
	sort?: MediaSort,
};

export type MediaReasons = {
	mediaId: string,
	/**  Pending reasons, most important first. */
	reasons: ReasonScore[],
};

export type MediaSort = 
/**  Capture date, newest first; undated last. */
"newest" | 
/**  Capture date, oldest first; undated last. */
"oldest" | 
/**  File name A→Z. */
"name" | 
/**  Largest files first. */
"largest" | 
/**  Review priority, highest first (photos without suggestions last). */
"priority";

export type MediaType = "image" | "video";

/**
 *  Items whose metadata/thumbnails changed; `removedIds` were merged into another
 *  record (moved files).
 */
export type MediaUpdatedEvent = {
	items: MediaItem[],
	removedIds: string[],
};

export type MomentaryFilter = "any" | "document" | "accidental";

/**  What to do when the original path is taken again. */
export type OnConflict = 
/**  Leave it in the trash and report it (the UI asks). */
"ask" | 
/**  Restore as "name (restaurada).ext". */
"rename";

export type OrganizeCounts = {
	/**  Groups, and extra copies in them (what could be freed). */
	exactGroups: number,
	exactExtra: number,
	visualGroups: number,
	visualExtra: number,
	similarGroups: number,
	sequences: number,
	lowQuality: number,
	momentary: number,
	screenshots: number,
	/**  Photos analysed / waiting (the counters grow while this is > 0). */
	analyzed: number,
	pending: number,
	/**  Photos with pending review suggestions, and photos in the trash (phase 5). */
	review: number,
	trash: number,
	/**  Trips/events waiting for "aceitar" or "ignorar" (phase 6). */
	eventSuggestions: number,
};

/**  Faces were regrouped into people (Pessoas, info panel). */
export type PeopleUpdatedEvent = null;

export type PersonName = {
	id: string,
	name: string,
};

export type PersonSummary = {
	id: string,
	/**  `None` = suggested group, not named yet. */
	name: string | null,
	hidden: boolean,
	/**  Photos of this person in the library. */
	photoCount: number,
	/**  Face shown as the person's picture (`pv://…/face/<id>`). */
	coverFaceId: string | null,
};

export type PlaceOption = {
	id: number,
	name: string,
	admin1: string | null,
	countryCode: string,
	count: number,
};

export type QualityFlag = "blurry" | "dark" | "overexposed" | "low_res" | 
/**  Almost no information (blank wall, lens cap, flat colour). */
"empty";

export type QualityLevel = "low" | "medium" | "high";

export type ReasonCount = {
	reason: ReviewReason,
	count: number,
};

export type ReasonScore = {
	reason: ReviewReason,
	score: number | null,
};

/**
 *  How much each reason weighs in the Review priority (0 = never suggest for it).
 *  Suggested levels in the UI: 1 (alta), 0.6 (normal), 0.3 (baixa), 0 (desligado).
 */
export type ReasonWeights = {
	exactDuplicate?: number | null,
	visualDuplicate?: number | null,
	similarSequence?: number | null,
	blurry?: number | null,
	dark?: number | null,
	overexposed?: number | null,
	lowResolution?: number | null,
	screenshot?: number | null,
	momentary?: number | null,
	accidental?: number | null,
	lowInformation?: number | null,
	example?: number | null,
};

/**  What "Reclassificar" redoes besides the suggestions (always redone). */
export type ReclassifyOptions = {
	/**
	 *  Accepted (not edited) events are detected again: those that come back keep their id
	 *  and stay accepted, the others go away. Edited events never change.
	 */
	accepted?: boolean,
	/**  Forget the ignored events: they can be suggested again. */
	ignored?: boolean,
};

export type RestoreConflict = {
	mediaId: string,
	filename: string,
	originalPath: string,
};

export type RestoreResult = {
	restored: string[],
	conflicts: RestoreConflict[],
	failed: TrashFailure[],
};

export type ReviewEntry = {
	reason: ReviewReason,
	/**  0–1: how sure the heuristic is. */
	score: number | null,
	status: ReviewStatus,
	/**  Similarity group, burst or example behind it. */
	groupId: string | null,
	/**  For `EXAMPLE`: the name of the example it looks like. */
	exampleName: string | null,
	decidedAt: string | null,
};

export type ReviewExample = {
	id: string,
	intent: ExampleIntent,
	name: string,
	/**  `data:image/webp;base64,…` */
	thumbnail: string,
	/**  Photo of the catalog it came from (absent for files picked from disk). */
	mediaId: string | null,
	createdAt: string,
	/**  Photos currently suggested because of it. */
	matches: number,
};

export type ReviewReason = "EXACT_DUPLICATE" | "VISUAL_DUPLICATE" | "SIMILAR_SEQUENCE" | "BLURRY" | "DARK" | "OVEREXPOSED" | "LOW_RESOLUTION" | "SCREENSHOT" | "MOMENTARY" | "ACCIDENTAL" | "LOW_INFORMATION" | "EXAMPLE";

export type ReviewSettings = {
	weights?: ReasonWeights,
	/**  Similarity (0–1) from which a photo counts as "like" one of the examples. */
	exampleSimilarity?: number | null,
	/**
	 *  Send to the operating system's trash instead of `.photovault-trash` (then it can
	 *  only be restored from there).
	 */
	useSystemTrash?: boolean,
	/**  Delete items older than this from the trash on startup; 0 = never (default). */
	autoPurgeDays?: number,
};

export type ReviewStatus = "pending" | "kept" | "ignored" | "trashed";

export type ReviewSummary = {
	/**  Photos with at least one pending suggestion. */
	pending: number,
	/**  Pending suggestions per reason (a photo counts once per reason). */
	byReason: ReasonCount[],
	/**  Bytes of the photos to review. */
	pendingBytes: number,
};

export type ScanCompleteEvent = ScanSummary;

export type ScanErrorEvent = {
	libraryId: string,
	error: ApiError,
};

export type ScanPhase = "discovering" | "indexing";

export type ScanProgress = {
	libraryId: string,
	phase: ScanPhase,
	processed: number,
	/**  0 while discovering (total still unknown). */
	total: number,
	currentPath: string,
};

export type ScanProgressEvent = ScanProgress;

export type ScanSummary = {
	libraryId: string,
	total: number,
	processed: number,
	newFiles: number,
	modifiedFiles: number,
	/**  Catalogued files no longer found (kept as `missing`, never deleted). */
	missingFiles: number,
	/**  Previously missing files that are back. */
	restoredFiles: number,
	errors: number,
	cancelled: boolean,
};

export type SceneScore = {
	value: string,
	label: string,
	/**  0–1: share among the scenes. */
	score: number | null,
};

export type TagCount = {
	tag: string,
	count: number,
};

export type Theme = "light" | "dark" | "system";

/**  Month bucket; `year` 0 = undated. */
export type TimelineBucket = {
	year: number,
	/**  1–12; 0 for undated. */
	month: number,
	count: number,
};

export type TrashEntry = {
	originalPath: string,
	deletedAt: string,
};

export type TrashFailure = {
	mediaId: string,
	filename: string,
	message: string,
};

export type TrashResult = {
	done: string[],
	failed: TrashFailure[],
};

export type TrashSummary = {
	count: number,
	bytes: number,
};

export type VolumeInfo = {
	/**  Human label: volume name on Windows, last mount-point component on Linux. */
	label: string,
	mountPoint: string,
	totalBytes: number,
	availableBytes: number,
	removable: boolean,
};

export type YearSummary = {
	year: number,
	count: number,
	cover: MediaItem | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

